/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f103xb.h"
#include "uart.h"
#include "timer1.h"
#include "dht11.h"
#include "gpio.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    TIMER1_Init();
    LED_Init();
    USART1_Init();
    DHT11_Init();

    USART1_SendString("Test\r\n");

    while(1)
    {
        DHT11_INPUT();
        if(DHT11_READ()) {
            USART1_SendString("PB0 is HIGH - Pull-up OK\r\n");
            LED_Toggle();
        } else {
            USART1_SendString("PB0 is LOW - Pull-up MISSING\r\n");
        }
        TIMER1_Delay_ms(65);
    }
}
